spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: world-service
          uri: lb://world-service
          predicates:
            - Path=/world/**
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true
server:
  port: 9102
logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN